# Generated by Django 6.0 on 2026-01-03 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sandwitches", "0007_alter_rating_score"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
