# Generated by Django 6.0.3 on 2026-04-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandwitches", "0025_alter_historicalrecipe_servings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="instagram_last_sync",
            field=models.DateTimeField(
                blank=True,
                help_text="The last time a recipe was successfully uploaded to Instagram",
                null=True,
            ),
        ),
    ]
