# Generated by Django 6.0.5 on 2026-07-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandwitches", "0028_remove_instagram_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("eink", "E-Ink")],
                default="light",
                max_length=10,
            ),
        ),
    ]
