plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - [
      "@semantic-release/exec",
      {
        prepareCmd: "uv version ${nextRelease.version}",
      },
    ]
  - [
      "@semantic-release/git",
      {
        message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        assets: ["CHANGELOG.md", "pyproject.toml"],
      },
    ]
  - "@semantic-release/github"

branches:
  - main