# Generated by Django 5.2.7 on 2025-11-03 19:23

import sandwitches.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandwitches", "0002_tag_alter_recipe_options_recipe_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=sandwitches.storage.HashedFilenameStorage(),
                upload_to="recipes/",
            ),
        ),
    ]
