---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: latest
serverless_language:
polling_url: "https://sandwitches.vandijke.xyz/api/v1/recipe-of-the-day\r\nhttps://sandwitches.vandijke.xyz/api/v1/users"
polling_headers: ''
polling_body: ''
id: 247547
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: bio
  name: About This Plugin
  category: entertainment
  field_type: author_bio
  description: Don't know what to make for lunch ? Be insipred by these daily sandwitches curtesey of my girlfriend.
  github_url: https://github.com/martynvdijke/sandwitches
  learn_more_url: https://sandwitches.vandijke.xyz/
  email_address: martyn@vandijke.xyz
- keyname: url
  field_type: url
  name: Addres of sandwitches instance
  description: URL
  placeholder: https://sandwitches.vandijke.xyz
  help_text: Please include http:// or https://
name: Sandwitches
description:
refresh_interval: 1440
